Fix AttributeError for OBJ files with vertices but no faces (#168)
<!--
Thank you for taking the time to make a pull request.

Please review our [contribution
guide](https://github.com/SeequentEvo/evo-data-converters/blob/main/CONTRIBUTING.md)
and our
[code of
conduct](https://github.com/SeequentEvo/evo-data-converters/blob/main/CONTRIBUTING.md)
before opening your first
pull request.
-->

## Description

<!-- Describe your proposed changes in detail -->

Fix the beloew AttributeError when importing a OBJ mesh with no faces. 
```
faces_array = np.asarray(mesh.faces) + np.sum([len(v) for v in vertices_tables])
AttributeError: 'PointCloud' object has no attribute 'faces'
```
When there is no faces in the OBJ file, the geometry in the `trimesh`
scene is a `PointCloud` object, as opposed to a `Trimesh` object which
it is if there is any faces.

## Checklist

- [x] I have read the contributing guide and the code of conduct